### ISSUE TITLE
FIR estimates for convolved variables

### ISSUE THREAD

**Issue by leotozzi88** [GatesLab/gimme#32]
Thank you very much for making this tool available to the research community! 

I would like to study directed connectivity in response to a task using fMRI, so I have used your GIMME algorithm using the conv_vars option for my events of interest. 

First of all, could you please confirm that the variable to convolve should be a binary variable of the same length as the timeseries, which in turn should be equal to the number of fMRI volumes acquired? This variable would have 1 for the volumes where the event is present and 0 in the ones where it's not. Is this correct? 

I also have a second question: GIMME uses FIR to fit a hemodynamic response at the subject level. How can I inspect the parameter estimates for this FIR at the single subject level (or at the group level)? Are these stored? 

Thank you very much!

**Comment by kgates** [comment]
Yes, you are correct that the variable to be convolved should be binary and the same length as the timeseries. Your description of the variable is accurate.

We actually do not provide this in the output. We have added it to the list of things to do.


_______________________________________
Katie (Kathleen) Gates, Ph.D. (she/her)
Associate Professor
Psychology and Neuroscience
344A Davie Hall
University of North Carolina
https://unc.zoom.us/my/katiegates

________________________________
From: Leonardo Tozzi ***@***.***>
Sent: Tuesday, April 5, 2022 6:57 PM
To: GatesLab/gimme ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GatesLab/gimme] FIR estimates for convolved variables (Issue #32)


Thank you very much for making this tool available to the research community!

I would like to study directed connectivity in response to a task using fMRI, so I have used your GIMME algorithm using the conv_vars option for my events of interest.

First of all, could you please confirm that the variable to convolve should be a binary variable of the same length as the timeseries, which in turn should be the number of fMRI volumes acquired? This variable would have 1 for the volumes where the event is present and 0 in the ones where it's not. Is this correct?

I also have a second question: GIMME uses FIR to fit a hemodynamic response at the subject level. How can I inspect the parameter estimates for this FIR at the single subject level (or at the group level)? Are these stored?

Thank you very much!

**Comment by leotozzi88** [comment]
Thank you very much for your answer!

**Comment by kgates** [comment]
Hello again, 

We have now added the HRF estimates to the output! If you run your gimme HRF analyses and save the output as an object (say, "outgimmeHRF") then you can access each individual's RF estimates. The first person's could be found at: outgimmeHRF$rf_est[[1]]. 

Please see our tutorial at https://tarheels.live/gimme/hrf-gimme/ for help with running HRF-GIMME.

Thanks for your patience!

**Comment by leotozzi88** [comment]
Thank you so much for adding this feature! 

I have tried updating GIMME and even installing from the Github and I can't see this field in my results. Am I doing something wrong? I saved the output of GIMME as follows (this is for a go/nogo task):

```
res<-gimme(            
  data = 'gonogo_gimme_test',      
  out = 'gonogo_gimme_test_out',           
  sep = ",",         
  header = TRUE,     
  ar = TRUE,         
  plot = TRUE, 
  subgroup = FALSE,   
  paths = NULL,       
  groupcutoff = .75,  
  subcutoff = .5,    
  exogenous = c("go", "nogo"),
  conv_vars = c("go", "nogo"), 
  conv_interval = 2.5,
  conv_length = 15, 
  standardize = TRUE
)

```


But then, in the res object, I don't see that field: 

`
> res$rf_est
NULL
`

Sorry if I am missing something obvious!

Thank you very much!

**Comment by kgates** [comment]
Hi there, 

We have been unable to replicate this error. Would you be able to share your data by chance? We would only need a couple of people. 

You can email gimme@unc.edu. 

Thanks.
