### ISSUE TITLE
Replacement error when using subgroup option

### ISSUE THREAD

**Issue by leotozzi88** [GatesLab/gimme#33]
Dear Experts, 

I am trying to use GIMME on a dataset of 270 individuals. When running the analysis with subgroup=FALSE, everything works fine. 

However, when I run it with subgroup=TRUE, I keep getting this error:

(...)
group-level pruning, subject 268 (...)
group-level pruning, subject 269 (...)
group-level pruning, subject 270 (...)
group-level pruning, subject 271 (...)
Error in `$<-.data.frame`(`*tmp*`, "ind_paths", value = list(NULL, NULL,  : 
  replacement has 271 rows, data has 273

It seems that GIMME is somehow creating a duplicate subject, in my case I see the same file appear twice, for subject 265 and 266 and then it crashes with this error. Note that the subjects are 270, so it seems like it's creating more subjects somehow.

Could you please advise on how to handle this? 

Thank you, 

Leonardo Tozzi

**Comment by kgates** [comment]
Hello,

Thanks for sharing this error. We haven't seen it.

Would it be possible to share the data so we can try to recreate it?

Katie

_______________________________________
Katie (Kathleen) Gates, Ph.D. (she/her)
Associate Professor
Psychology and Neuroscience
344A Davie Hall
University of North Carolina
https://unc.zoom.us/my/katiegates

________________________________
From: Leonardo Tozzi ***@***.***>
Sent: Wednesday, April 13, 2022 1:05 PM
To: GatesLab/gimme ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GatesLab/gimme] Replacement error when using subgroup option (Issue #33)


Dear Experts,

I am trying to use GIMME on a dataset of 270 individuals. When running the analysis with subgroup=FALSE, everything works fine.

However, when I run it with subgroup=TRUE, I keep getting this error:

(...)
group-level pruning, subject 268 (...)
group-level pruning, subject 269 (...)
group-level pruning, subject 270 (...)
group-level pruning, subject 271 (...)
Error in $<-.data.frame(*tmp*, "ind_paths", value = list(NULL, NULL, :
replacement has 271 rows, data has 273

It seems that GIMME is somehow creating a duplicate subject, in my case I see the same file appear twice, for subject 265 and 266 and then it crashes with this error.

Could you please advise on how to handle this?

Thank you,

Leonardo Tozzi

**Comment by leotozzi88** [comment]
Dear Katie, 

Of course! I will send you an email with the data. 

Thank you very much, 

Leonardo Tozzi

**Comment by kaduffy** [comment]
Marking this issue as resolved after discussing with Dr. Tozzi -- it turned out to be a glitch with Google Drive, and not an issue specific to GIMME. If anyone encounters a similar issue when using Google Drive to store their data and output files, they should check if downloading the files and running locally resolves the issue.
