### ISSUE TITLE
$ operator error

### ISSUE THREAD

**Issue by CFGEIER** [GatesLab/gimme#36]
Hi,
After installing the most current versions of R and R studio, I got the following error message when trying to run GIMME:
 
Error in x$lhs : $ operator is invalid for atomic vectors
 
Another user in my lab also got this error independently, so I suspect it might be some incompatibility deriving from the r update?  Can someone please advise?
 
Thank you!!
Chuck

**Comment by CFGEIER** [comment]
Quick update- seems to work after setting standardize=TRUE. Sorry for the hassle!

**Comment by kgates** [comment]
That's great to know! We haven't gotten a chance to look into this error but it's on the list of to dos.

Would you be able to share the data with ***@***.*** by chance? This way we can replicate the problem. No big deal if you can't share it.
_______________________________________
Katie (Kathleen) Gates, Ph.D. (she/her)
Associate Professor
Psychology and Neuroscience
344A Davie Hall
University of North Carolina
https://unc.zoom.us/my/katiegates

________________________________
