### ISSUE TITLE
A doubt on S-GIMME

### ISSUE THREAD

**Issue by iago-pssjd** [GatesLab/gimme#39]
Hi,

I would like to ask you if to implement the S-GIMME algorithm have I to use the same GIMME function (gimmeSEM) with possibly diferent options like `subgroup` and `confirm_subgroup`? 

I ask about it, because this is the R package referred to in the paper Unsupervised Classification During Time-Series Model Building, where it is claimed that 
> S-GIMME is freely available within an R package (Lane, Gates, & Molenaar, 2016) .
> Lane, S. T., Gates, K. M., & Molenaar, P. C. M. (2016). Gimme: Group iterative multiple model estimation [Computer Software]. Retrieved from https://CRAN.Rproject.org/package=gimme

Thank you!

**Comment by kgates** [comment]
Hi! 

You are absolutely right - you'd use the same function. 

Here's a tutorial on [how to use the unsupervised classification approach](https://tarheels.live/gimme/subgrouping-gimme/) (S-GIMME). 

Here's another tutorial on how to do [gimme analyses with confirmatory subgroups](https://tarheels.live/gimme/tutorials/confirmatory-subgroup-gimme/). 

We know these tutorials are hard to find so we're working on getting them into vignette form for the package. 

Thanks for reaching out about this! 

Katie

**Comment by iago-pssjd** [comment]
@kgates thank you!
